//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 05 20:23:01 CST 2013
//----------------------------------------------------

package simpl.parser;

/**
 * CUP generated interface containing symbol constants.
 */
public interface Symbols {
    /* terminals */ int CONS = 31;
    int ORELSE = 18;
    int GE = 30;
    int UNIT = 32;
    int LPAREN = 38;
    int SEMI = 37;
    int REF = 3;
    int RPAREN = 39;
    int REC = 5;
    int NOT = 16;
    int LT = 27;
    int FN = 4;
    int NIL = 2;
    int IN = 7;
    int COMMA = 36;
    int DIV = 22;
    int NUM = 41;
    int ASSIGN = 34;
    int IF = 9;
    int ID = 42;
    int LE = 28;
    int EOF = 0;
    int APP = 40;
    int TRUE = 14;
    int error = 1;
    int MUL = 21;
    int ADD = 19;
    int MOD = 23;
    int EQ = 25;
    int ARROW = 33;
    int NEG = 24;
    int ELSE = 11;
    int ANDALSO = 17;
    int WHILE = 12;
    int LET = 6;
    int THEN = 10;
    int NE = 26;
    int END = 8;
    int FALSE = 15;
    int GT = 29;
    int SUB = 20;
    int DEREF = 35;
    int DO = 13;
}
